### ISSUE TITLE
Lab references pressing OPEN IDE but there is no button

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/js-from-dom-to-node#35]
This lab says:

`To launch the Learn IDE, click the blue Open button at the top of this page. This should download the 
lesson to your IDE and open the IDE. If you need to re-download the IDE, you can do so here.`

But there is no button, only for the sandbox.

**Comment by justinddaniel** [comment]
Correction: there is now not even a sandbox button either :(

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @FreeBreadsticks.

We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
