### ISSUE TITLE
can't access code folder in From DOM To Node and the IDE

### ISSUE THREAD

**Issue by jbrumfield19** [learn-co-curriculum/js-from-dom-to-node#36]
There isn't an option to open the code folder mentioned and shown in the lesson.

**Comment by renaefae** [comment]
I have the same issue.

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @jbrumfield19.

We have updated this lesson so that it correctly displays the Open IDE button, behaves like a code along, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
