### ISSUE TITLE
Unable to upload it to github & proceed to next lesson.

### ISSUE THREAD

**Issue by satyasrib** [learn-co-curriculum/js-from-dom-to-node#37]
![capture](https://user-images.githubusercontent.com/40673351/46784419-e3b89480-cce2-11e8-831d-afbad3739e4a.JPG)

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @satyasrib.

We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
