### ISSUE TITLE
IDE Unavailable

### ISSUE THREAD

**Issue by ArielHicks** [learn-co-curriculum/js-from-dom-to-node#38]
I have checked my browser settings and the IDE should be appealing but all I have access to is the sandbox. Any thoughts? Thanks!

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @ArielHicks.

We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
