### ISSUE TITLE
Hey. I've reported this before, but

### ISSUE THREAD

**Issue by davidsollesse** [learn-co-curriculum/js-from-dom-to-node#39]
Can't submit my work through a cloned file. It doesn't recognise the directory. I took a print screen anyway :P

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @davidsollesse.

We have updated this lesson so that it correctly displays the Open IDE button and should work properly as a code along. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
