### ISSUE TITLE
No Open IDE button, nor is there a Sandbox button

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/js-from-dom-to-node#40]
Please fix this! :)

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @justinddaniel.

We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
