### ISSUE TITLE
I don't see open IDE button

### ISSUE THREAD

**Issue by amerdoko** [learn-co-curriculum/js-from-dom-to-node#41]
![open ide button does not appear](https://user-images.githubusercontent.com/9827366/46919574-1c8c8e00-cfaf-11e8-8974-ae5b665e2735.JPG)

**Comment by asjarzeb** [comment]
Same issue here :(

**Comment by MassiveXeffectN9** [comment]
me too!!

**Comment by JohnThursday** [comment]
Ditto on that one. I get a button for the following lesson, but not for this one.

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @amerdoko.

Sorry for the confusion this lesson has caused. We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
