### ISSUE TITLE
Opening Project

### ISSUE THREAD

**Issue by JRamos193** [learn-co-curriculum/js-from-dom-to-node#42]
Hi!

Im unable to open the project required to continue the course.  I have IDE 3 downloaded and Atom as well but at the top of the page, "sandbox" is the only option given to me when it doesn't offer the js file.

Thank you.

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @JRamos193.

We have updated this lesson so that it correctly displays the Open IDE button instead of the Sandbox and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
