### ISSUE TITLE
IDE Not Loading

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/js-from-dom-to-node#46]
Hi, when I open the IDE in my Chrome browser the files are not displayed and I am unable to type into the terminal. Basically, the IDE opens up and I am in the folder "first-ide-lab-ghe-compat-bootcamp-prep-001" and am able to type in the text editor only. I've tried reading a little on why this may be but haven't found a solution yet. Any help is much appreciated. Thanks!

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @ghost.

Sorry for the confusion this lesson has caused. We have updated this lesson so that it should now behave correctly as a code along. If you revisit the lesson, you should now be able to open up the IDE to the proper directory.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
