### ISSUE TITLE
IDE blue button 

### ISSUE THREAD

**Issue by MassiveXeffectN9** [learn-co-curriculum/js-from-dom-to-node#47]
after multiple tries of making sure my IDE in the settings was set to browser I still couldn't get the IDE button.

**Comment by maxwellbenton** [comment]
Thank you providing feedback, @MassiveXeffectN9.

Sorry for the confusion this lesson has caused. We have updated this lesson so that it correctly displays the Open IDE button and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
