### ISSUE TITLE
Where to download the files?

### ISSUE THREAD

**Issue by winzardv11** [learn-co-curriculum/js-from-dom-to-node#49]
I couldn't find the files used

**Comment by maxwellbenton** [comment]
Thank you for providing feedback, @winzardv11.

We apologize for the confusion caused by this lab. We have updated the materials so that the Open IDE button will now appear, updated the instructions and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
