### ISSUE TITLE
No open IDE button

### ISSUE THREAD

**Issue by MrGametop1** [learn-co-curriculum/js-from-dom-to-node#51]
You write the following:
"To launch the Learn IDE, click the blue Open button at the top of this page. This should download the lesson to your IDE and open the IDE. If you need to re-download the IDE, you can do so here."

Picture of the site:
https://gyazo.com/f5ea6b0d3fb4ba43e750d4b1fb722344

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @MrGametop1.

We have updated this lesson so that it correctly works as a code along and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
