### ISSUE TITLE
No Open IDE Button, No Labs folder

### ISSUE THREAD

**Issue by disarrangedorder** [learn-co-curriculum/js-from-dom-to-node#53]
Like others have mentioned, there's no Open IDE button. 

Tried to manually do it. I forked it over from github, it saved onto my computer. But when it opens, it always opens up "Sandbox" instead. When I looked for the files on my computer, it exists there  and I have to manually open the index.js by right clicking and open Learn. I tried following the instructions on this page, but then had an error message regarding the file path location. 

Tried to trouble shoot by following these instructions that are on the lesson:
"If you see code, we need to go into our labs folder first. To do this type cd labs. Now if should see labs next to the clock. We have to go one more folder in. I know this by looking at the folder structure on the left. See how labs is in code and js-from-dom-to-node is in labs?..."

There's a problem with the above because no where does a "code" or "labs" folders even exist on my computer yet. No are there any specific instructions how or where we should put those folders.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @tedsazon.

We have updated the materials so that this code along displays the correct button, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
