### ISSUE TITLE
No Open button

### ISSUE THREAD

**Issue by tedsazon** [learn-co-curriculum/js-from-dom-to-node#54]
There's no open button to start the Lab.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @tedsazon.

We have updated the materials so that this code along displays the correct button, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
